[project]
name = "histopathology-pnw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mateusz Wojtaszek", email = "mateusz.wojtaszek@icloud.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
histopathology-pnw = "histopathology_pnw:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "dvc[ssh]>=3.67.1",
]
